USE [master]
GO
/****** Object:  Database [SkiCompetition]    Script Date: 29.7.2021 г. 17:58:03 ******/
CREATE DATABASE [SkiCompetition]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SkiCompetition', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SkiCompetition.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SkiCompetition_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SkiCompetition_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SkiCompetition] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SkiCompetition].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SkiCompetition] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SkiCompetition] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SkiCompetition] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SkiCompetition] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SkiCompetition] SET ARITHABORT OFF 
GO
ALTER DATABASE [SkiCompetition] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SkiCompetition] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SkiCompetition] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SkiCompetition] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SkiCompetition] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SkiCompetition] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SkiCompetition] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SkiCompetition] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SkiCompetition] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SkiCompetition] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SkiCompetition] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SkiCompetition] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SkiCompetition] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SkiCompetition] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SkiCompetition] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SkiCompetition] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SkiCompetition] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SkiCompetition] SET RECOVERY FULL 
GO
ALTER DATABASE [SkiCompetition] SET  MULTI_USER 
GO
ALTER DATABASE [SkiCompetition] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SkiCompetition] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SkiCompetition] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SkiCompetition] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SkiCompetition] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SkiCompetition] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SkiCompetition', N'ON'
GO
ALTER DATABASE [SkiCompetition] SET QUERY_STORE = OFF
GO
USE [SkiCompetition]
GO
/****** Object:  View [dbo].[SkiersInfo]    Script Date: 29.7.2021 г. 17:58:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[SkiersInfo]
	AS SELECT StartList.ID, StartList.FirstName, StartList.LastName, StartList.Sex, StartList.Team, RankTable.SkierID, RankTable.Rank 
	FROM dbo.StartList 
	left join [dbo].[RankTable] on RankTable.SkierID = StartList.ID
GO
/****** Object:  Table [dbo].[Competitors]    Script Date: 29.7.2021 г. 17:58:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Competitors](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Sex] [varchar](20) NOT NULL,
	[TeamID] [int] NOT NULL,
	[TimeInMs] [time](7) NULL,
 CONSTRAINT [PK_StartList] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TableTimes]    Script Date: 29.7.2021 г. 17:58:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TableTimes](
	[CompetitorID] [int] NOT NULL,
	[TimeInMs] [time](7) NOT NULL,
	[DateTime] [datetime2](7) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TeamTable]    Script Date: 29.7.2021 г. 17:58:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TeamTable](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TeamName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TeamTable] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Competitors]  WITH CHECK ADD  CONSTRAINT [FK_Competitors_TeamTable] FOREIGN KEY([TeamID])
REFERENCES [dbo].[TeamTable] ([ID])
GO
ALTER TABLE [dbo].[Competitors] CHECK CONSTRAINT [FK_Competitors_TeamTable]
GO
/****** Object:  StoredProcedure [dbo].[FilterByLastName]    Script Date: 29.7.2021 г. 17:58:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[FilterByLastName]
	@LastName varchar(50)
	
AS
begin 
select *
from dbo.StartList
where LastName = @LastName;
end
GO
USE [master]
GO
ALTER DATABASE [SkiCompetition] SET  READ_WRITE 
GO
